"""add showing status

Revision ID: cb9468583be0
Revises: cc0870533042
Create Date: 2026-05-28 20:12:21.161279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9468583be0'
down_revision: Union[str, Sequence[str], None] = 'cc0870533042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genres', ['name'])
    showing_status_enum = sa.Enum('active', 'cancelled', name='showing_status')
    showing_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'showings',
        sa.Column('status', showing_status_enum, nullable=False, server_default='active'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showings', 'status')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_column('showings', 'status')
    sa.Enum(name='showing_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
